# 网站基本信息
title: "优秀币导航"
description: "分享各大虚拟币交易所最新官网访问备用入口链接地址"
url: "https://youxiubi.github.io" # 替换成你的 GitHub 页面 URL
baseurl: ""  # 如果你放在子目录下，比如 "my-site"，则填写 "/my-site"

# 主题配置
theme: minima

# 设置首页使用 README.md 内容
defaults:
  - scope:
      path: "" # 表示所有路径
      type: "readme"  # 默认加载 README.md
    values:
      layout: "home"

# 文章配置
paginate: 10  # 每页显示 10 篇文章

# 归档页面
permalink: /archive/

# 存储文章和页面的位置
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
    layout: post

# 启用未来的文章
future: true

# 启用草稿
drafts: true

# 显示所有文章
posts_dir: "_posts"

# SEO 配置
social:
  twitter: "youxiubi" # 可选，填入你的 Twitter 账号，或者移除此项

# 其他可选配置
markdown: kramdown
highlighter: rouge
